### ISSUE TITLE
Change run command containing `OTEL_METRICS_EXPORTER=none` or `--traces_exporter otlp_proto_http`

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io-old#591]
https://signoz.io/search/?q=OTEL_METRICS_EXPORTER+%3Dnone
https://signoz.io/search/?q=otlp_proto_http

help might be needed from @srikanthccv 

Error notified by a user

```
Transient error StatusCode.UNAVAILABLE encountered while exporting metrics, retrying in Nones.
Exception while exporting metrics 'NoneType' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 305, in _export
    self._client.Export(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:34.193.244.185:4318 {created_time:"2022-10-24T22:11:40.528905+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 499, in _receive_metrics
    self._exporter.export(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py", line 265, in export
    return self._export(data=metrics_data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 345, in _export
    sleep(delay)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

recommended by @srikanthccv. We might even have a unified command for both metrics and traces
```
OTEL_RESOURCE_ATTRIBUTES=service.name="TestApp" OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317/" opentelemetry-instrument --traces_exporter otlp_proto_grpc --metrics_exporter otlp_proto_grpc flask run
```

**Comment by srikanthccv** [comment]
Will update this when this gets released https://github.com/open-telemetry/opentelemetry-python/pull/3027

**Comment by pranay01** [comment]
@srikanthccv Seems like above PR is released right? Should we update the docs?

**Comment by srikanthccv** [comment]
No, it got merged but has not been released yet.
